/** Styles */
import './source/styles/reset.css'
import './source/styles/globals.scss'

/** Next Imports */
import { Urbanist, Mulish } from "next/font/google"
import Footer from './source/components/common/footer';

const Urbanist_Font = Urbanist({
    subsets: ["latin"],
    variable: '--Urbanist_Font'
})

const Mulish_Font = Mulish({
    subsets: ["latin"],
    variable: '--Mulish_Font'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${Urbanist_Font.variable} ${Mulish_Font.variable}`}>
				{children}
				<Footer />
			</body>
		</html>
	);
}
